version: '3'

services:
  logmyip:
    build: .
    ports:
      - "52899:52899"
    environment:
      - RedisAddr=db:6379
      - RedisPass=${REDIS_PASSWORD}
    depends_on:
      - db
  
  db:
    image: redis:latest
    command: redis-server --save 10 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - lmip_db:/data
  
volumes:
  lmip_db:

